# Generated by Django 4.2.7 on 2026-03-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('dokumenti', 'Документы'), ('informatsiya_postupayushchim', 'Информация поступающим'), ('obrazovanie_invalidov', 'Образование инвалидов'), ('obshchezhitie', 'Общежитие'), ('prikazi_o_zachislenii', 'Приказы о зачислении'), ('spiski_postupayushchikh', 'Списки поступающих'), ('usloviya_priyoma', 'Условия приёма'), ('zayavlenie_o_priyome_i_dogovor', 'Заявление о приёме и договор'), ('osnovnye_svedeniya', 'Основные сведения'), ('dokumenty_i_licenzii', 'Документы и лицензии'), ('obrazovanie', 'Образование'), ('rukovodstvo', 'Руководство'), ('pedagogicheskiy_sostav', 'Педагогический состав'), ('materialno_tekhnicheskoe', 'Материально-техническое обеспечение'), ('platnye_uslugi', 'Платные образовательные услуги'), ('finansovo_khozyaystvennaya', 'Финансово-хозяйственная деятельность'), ('vakantnyye_mesta', 'Вакантные места'), ('stipendii', 'Стипендии и меры поддержки'), ('mezhdunarodnoe', 'Международное сотрудничество'), ('organizatsiya_pitaniya', 'Организация питания'), ('obrazovatelnye_standarty', 'Образовательные стандарты'), ('pedagogicheskiy_sostav', 'Педагогический состав'), ('attestatsiya', 'Аттестация педагогических работников'), ('metodicheskiy_kabinet', 'Методический кабинет'), ('konferentsiya', 'Студенческая научно-практическая конференция'), ('student_docs', 'Документы студентам'), ('ssk_docs', 'Документы ССК'), ('antinarko_docs', 'Антинарко'), ('profilaktika_docs', 'Профилактика'), ('other', 'Прочее')], default='other', max_length=100, verbose_name='Категория'),
        ),
    ]
