# Generated by Django 4.2.7 on 2026-04-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_page_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
    ]
