# Generated by Django 4.2.7 on 2026-04-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_page_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок раздела')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sections', to='cms.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Раздел документов',
                'verbose_name_plural': 'Разделы документов',
                'ordering': ['order', 'title'],
                'unique_together': {('page', 'category')},
            },
        ),
    ]
