# Generated by Django 4.2.7 on 2026-04-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_add_document_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год поступления')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Год поступления',
                'verbose_name_plural': 'Годы поступления',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('opop', 'ОПОП (основная программа)'), ('rup', 'Рабочий учебный план'), ('calendar', 'Календарный учебный график'), ('annotation', 'Аннотации рабочих программ'), ('fos', 'Фонд оценочных средств'), ('practice', 'Программа практики'), ('other', 'Прочее')], default='opop', max_length=50, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='edu_programs/%Y/', verbose_name='Файл')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cms.admissionyear', verbose_name='Год поступления')),
            ],
            options={
                'verbose_name': 'Документ программы',
                'verbose_name_plural': 'Документы программы',
                'ordering': ['order', 'doc_type'],
            },
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код специальности')),
                ('title', models.CharField(max_length=300, verbose_name='Название специальности')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Квалификация')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Срок обучения')),
                ('form', models.CharField(blank=True, default='Очная', max_length=100, verbose_name='Форма обучения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_programs', to='cms.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='admissionyear',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='cms.educationalprogram', verbose_name='Программа'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionyear',
            unique_together={('program', 'year')},
        ),
    ]
