# Generated by Django 6.0.4 on 2026-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_add_educational_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Файл'),
        ),
    ]
