# Generated by Django 5.2.14 on 2026-06-16 17:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_homeblock_homequicklink_homepage_bento_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Код')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© 2026 Техникум. Все права защищены.', max_length=300, verbose_name='Копирайт'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_tagline',
            field=models.CharField(blank=True, default='Качество образование — наша главная цель', max_length=300, verbose_name='Текст в подвале'),
        ),
        migrations.AlterField(
            model_name='homequicklink',
            name='style',
            field=models.CharField(choices=[('bento-g1', 'Зелёный 1 (большая)'), ('bento-g2', 'Зелёный 2'), ('bento-g3', 'Зелёный 3'), ('bento-g4', 'Зелёный 4'), ('bento-g5', 'Зелёный 5'), ('bento-g6', 'Зелёный 6'), ('bento-g7', 'Зелёный 7'), ('bento-g8', 'Зелёный 8'), ('bento-contacts', 'Контакты (белая)')], default='bento-g2', max_length=30, verbose_name='Стиль'),
        ),
    ]
