# Generated by Django 5.2.14 on 2026-06-05 07:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_document_external_url_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст / HTML'), ('welcome', 'Приветствие'), ('director', 'Обращение директора'), ('html', 'Произвольный HTML')], default='text', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержимое')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Блок главной',
                'verbose_name_plural': 'Блоки главной',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('icon', models.CharField(default='fas fa-link', max_length=100, verbose_name='Иконка FontAwesome')),
                ('style', models.CharField(choices=[('bento-g1', 'Зелёный 1 (большая)'), ('bento-g2', 'Зелёный 2'), ('bento-g3', 'Зелёный 3'), ('bento-g4', 'Зелёный 4'), ('bento-g5', 'Зелёный 5'), ('bento-g6', 'Зелёный 6'), ('bento-contacts', 'Контакты (белая)')], default='bento-g2', max_length=30, verbose_name='Стиль')),
                ('is_large', models.BooleanField(default=False, verbose_name='Большая плитка')),
                ('is_contacts', models.BooleanField(default=False, verbose_name='Блок контактов')),
                ('contacts_list', models.TextField(blank=True, help_text='Пример: fa-phone|8-988-480-06-92|tel:+79884800692', verbose_name='Список контактов (каждая строка: иконка|текст|ссылка)')),
                ('stat_num', models.CharField(blank=True, max_length=20, verbose_name='Число статистики')),
                ('stat_label', models.CharField(blank=True, max_length=100, verbose_name='Подпись статистики')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Открывать в новой вкладке')),
            ],
            options={
                'verbose_name': 'Быстрая ссылка',
                'verbose_name_plural': 'Быстрые ссылки главной',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='bento_title',
            field=models.CharField(default='Быстрые ссылки', max_length=200, verbose_name='Заголовок быстрых ссылок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email контактов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_map_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на карту (iframe)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон контактов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_phone2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Доп. телефон'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_title',
            field=models.CharField(default='Контакты', max_length=200, verbose_name='Заголовок контактов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hotline_text',
            field=models.TextField(blank=True, verbose_name='Текст телефона доверия'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_email',
            field=models.EmailField(blank=True, default='kktbel@mail.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_name',
            field=models.CharField(default='АНЧ ПОО «Краснодарский кооперативный техникум крайпотребсоюза»', max_length=300, verbose_name='Название техникума'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_phone',
            field=models.CharField(blank=True, default='8(86155)2-27-83', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_tagline',
            field=models.CharField(blank=True, default='Качество + Креатив + Творчество', max_length=200, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_telegram',
            field=models.URLField(blank=True, default='https://t.me/belkkt', verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_vk',
            field=models.URLField(blank=True, default='https://vk.com/belkkt', verbose_name='ВКонтакте'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialties_count',
            field=models.CharField(blank=True, default='7', max_length=10, verbose_name='Число специальностей'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialties_image',
            field=models.ImageField(blank=True, upload_to='homepage/', verbose_name='Фото блока специальностей'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialties_label',
            field=models.CharField(blank=True, default='Образование', max_length=100, verbose_name='Подпись блока специальностей'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialties_list',
            field=models.TextField(blank=True, help_text='Пример: fa-plane|Туризм и гостеприимство|43.02.16', verbose_name='Список специальностей (каждая с новой строки: иконка|название|код)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialties_text',
            field=models.TextField(blank=True, default='Среднее профессиональное образование по очной форме. Поступление после 9 и 11 классов.', verbose_name='Текст специальностей'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialties_title',
            field=models.CharField(default='Мы обучаем востребованным специальностям', max_length=300, verbose_name='Заголовок специальностей'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vov_image',
            field=models.ImageField(blank=True, upload_to='homepage/', verbose_name='Изображение ВОВ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vov_text',
            field=models.CharField(blank=True, default='Победа в Великой Отечественной войне 1941-1945', max_length=300, verbose_name='Текст блока ВОВ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('dokumenti', 'Документы'), ('informatsiya_postupayushchim', 'Информация поступающим'), ('obrazovanie_invalidov', 'Образование инвалидов'), ('obshchezhitie', 'Общежитие'), ('prikazi_o_zachislenii', 'Приказы о зачислении'), ('spiski_postupayushchikh', 'Списки поступающих'), ('usloviya_priyoma', 'Условия приёма'), ('zayavlenie_o_priyome_i_dogovor', 'Заявление о приёме и договор'), ('osnovnye_svedeniya', 'Основные сведения'), ('dokumenty_i_licenzii', 'Документы и лицензии'), ('obrazovanie', 'Образование'), ('rukovodstvo', 'Руководство'), ('pedagogicheskiy_sostav', 'Педагогический состав'), ('materialno_tekhnicheskoe', 'Материально-техническое обеспечение'), ('platnye_uslugi', 'Платные образовательные услуги'), ('finansovo_khozyaystvennaya', 'Финансово-хозяйственная деятельность'), ('vakantnyye_mesta', 'Вакантные места'), ('stipendii', 'Стипендии и меры поддержки'), ('mezhdunarodnoe', 'Международное сотрудничество'), ('organizatsiya_pitaniya', 'Организация питания'), ('obrazovatelnye_standarty', 'Образовательные стандарты'), ('pedagogicheskiy_sostav', 'Педагогический состав'), ('attestatsiya', 'Аттестация педагогических работников'), ('metodicheskiy_kabinet', 'Методический кабинет'), ('konferentsiya', 'Студенческая научно-практическая конференция'), ('student_docs', 'Документы студентам'), ('trudoustrojstvo_docs', 'Трудоустройство'), ('ssk_docs', 'Документы ССК'), ('antinarko_docs', 'Антинарко'), ('antikorrupciya_docs', 'Антикоррупция'), ('profilaktika_docs', 'Профилактика'), ('other', 'Прочее')], default='other', max_length=100, verbose_name='Категория'),
        ),
    ]
