# Generated by Django 6.0.6 on 2026-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_content_table_and_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (для карточки)'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-graduation-cap', help_text='Например: fas fa-calculator', max_length=100, verbose_name='Иконка FontAwesome'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='image',
            field=models.ImageField(blank=True, upload_to='programs/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной'),
        ),
    ]
